# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FileSplitUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class FileSplit_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 604)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 9, 761, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.lineEdit_wenjian = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_wenjian.setObjectName("lineEdit_wenjian")
        self.lineEdit_wenjian.setReadOnly(True)
        self.horizontalLayout_2.addWidget(self.lineEdit_wenjian)
        self.pushButton_wenjian = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_wenjian.setObjectName("pushButton_wenjian")
        self.horizontalLayout_2.addWidget(self.pushButton_wenjian)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.lineEdit_lujin = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_lujin.setObjectName("lineEdit_lujin")
        self.lineEdit_lujin.setReadOnly(True)
        self.horizontalLayout.addWidget(self.lineEdit_lujin)
        self.pushButton_lujin = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_lujin.setObjectName("pushButton_lujin")
        self.horizontalLayout.addWidget(self.pushButton_lujin)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_hangshu = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_hangshu.setObjectName("lineEdit_hangshu")
        self.horizontalLayout_3.addWidget(self.lineEdit_hangshu)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.pushButton_caifen = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_caifen.setObjectName("pushButton_caifen")
        self.horizontalLayout_3.addWidget(self.pushButton_caifen)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.textout_log = QtWidgets.QTextEdit(self.centralwidget)
        self.textout_log.setGeometry(QtCore.QRect(20, 240, 761, 301))
        self.textout_log.setObjectName("textout_log")
        self.textout_log.setReadOnly(True)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "文件拆分工具"))
        self.label_5.setText(_translate("MainWindow", "需要拆分的文件："))
        self.pushButton_wenjian.setText(_translate("MainWindow", "选择文件..."))
        self.label_4.setText(_translate("MainWindow", "拆分后的路径："))
        self.pushButton_lujin.setText(_translate("MainWindow", "选择路径..."))
        self.label_3.setText(_translate("MainWindow", "每个文件行数"))
        self.pushButton_caifen.setText(_translate("MainWindow", "开始拆分"))
